language: java
before_script: ./build.sh pom.xml
script: export MAVEN_OPTS="-Xmx1024m" && mvn test --quiet -Dlogback.configurationFile=test/resources/logback-test.xml
addons:
  hostname: short-hostname
jdk:
  - oraclejdk8
notifications:
    email: false
